Ingredient.create(name: 'Light rum')
Ingredient.create(name: 'Gin')
Ingredient.create(name: 'Dark rum')
Ingredient.create(name: 'Sweet Vermouth')
Ingredient.create(name: 'Strawberry schnapps')
Ingredient.create(name: 'Scotch')
Ingredient.create(name: 'Brandy')
Ingredient.create(name: 'Triple sec')
Ingredient.create(name: 'Southern comfort')
Ingredient.create(name: 'tea')
Ingredient.create(name: 'Champagne')
Ingredient.create(name: 'Amaretto')
Ingredient.create(name: 'Dry Vermouth')
Ingredient.create(name: 'Coffee liqueur')
Ingredient.create(name: 'Bourbon')
Ingredient.create(name: 'Tequila')
Ingredient.create(name: 'Vodka')
Ingredient.create(name: 'Bitters')
Ingredient.create(name: 'Sugar')
Ingredient.create(name: 'Kahlua')
Ingredient.create(name: 'Watermelon')
Ingredient.create(name: 'Lime')
Ingredient.create(name: 'Bitters')
Ingredient.create(name: 'lemon')
Ingredient.create(name: 'strawberry')
